apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: loggings.capabilities.morningspace.io
spec:
  group: capabilities.morningspace.io
  names:
    kind: Logging
    plural: loggings
  claimNames:
    kind: LoggingClaim
    plural: loggingclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  esVersion:
                    description: The Elasticsearch version
                    type: string
                  kibanaVersion:
                    description: The Kibana version
                    type: string
                required:
                  - esVersion
                  - kibanaVersion